/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package practica3;

import java.awt.Color;
import java.util.Objects;
import javax.swing.JComboBox;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;

/**
 *
 * @author Néstor Ojeda
 */
public class drawUI extends javax.swing.JFrame {


    /**
     * Creates new form drawUI
     */
    public drawUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        optionPanel = new javax.swing.JPanel();
        backgroundLabel = new javax.swing.JLabel();
        pencilLabel = new javax.swing.JLabel();
        backgroundComboBox = new javax.swing.JComboBox<>();
        pencilComboBox = new javax.swing.JComboBox<>();
        drawPanel = new practica3.DrawablePanel();
        authorsLabel = new javax.swing.JLabel();

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Estela");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        optionPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        optionPanel.setToolTipText("");

        backgroundLabel.setText("Fondo");

        pencilLabel.setText("Pincel");

        backgroundComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Blanco", "Azul", "Rojo", "Verde", "Amarillo" }));
        backgroundComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backgroundComboBoxActionPerformed(evt);
            }
        });

        pencilComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Negro", "Azul", "Verde", "Rojo", "Amarillo" }));
        pencilComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pencilComboBoxActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout optionPanelLayout = new javax.swing.GroupLayout(optionPanel);
        optionPanel.setLayout(optionPanelLayout);
        optionPanelLayout.setHorizontalGroup(
            optionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(optionPanelLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(backgroundLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(backgroundComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(pencilLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pencilComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(417, Short.MAX_VALUE))
        );
        optionPanelLayout.setVerticalGroup(
            optionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(optionPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(optionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(backgroundComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(backgroundLabel)
                    .addComponent(pencilLabel)
                    .addComponent(pencilComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        drawPanel.setBackground(new java.awt.Color(255, 255, 255));
        drawPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        drawPanel.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                drawPanelMouseMoved(evt);
            }
        });

        javax.swing.GroupLayout drawPanelLayout = new javax.swing.GroupLayout(drawPanel);
        drawPanel.setLayout(drawPanelLayout);
        drawPanelLayout.setHorizontalGroup(
            drawPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        drawPanelLayout.setVerticalGroup(
            drawPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 706, Short.MAX_VALUE)
        );

        authorsLabel.setText("Daniel Delgado Perera y Néstor Ojeda González");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(optionPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(drawPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(authorsLabel)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(optionPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(drawPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(authorsLabel)
                .addGap(7, 7, 7))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    private void backgroundComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backgroundComboBoxActionPerformed
        JComboBox cb = (JComboBox)evt.getSource();
        switch((String) Objects.requireNonNull(cb.getSelectedItem())){
            case "Azul":
                drawPanel.changeBackground(new Color(135, 199, 255));
                break;
            case "Rojo":
                drawPanel.changeBackground(new Color(237, 57, 57));
                break;
            case "Verde":
               drawPanel.changeBackground(new Color(106,222,116));
               break;
            case "Amarillo":
               drawPanel.changeBackground(new Color(248, 252, 131));
               break;
            case "Blanco":
               drawPanel.changeBackground(Color.white);
               break;
        }
    }//GEN-LAST:event_backgroundComboBoxActionPerformed

    private void pencilComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pencilComboBoxActionPerformed
        JComboBox cb = (JComboBox)evt.getSource();
        switch((String) Objects.requireNonNull(cb.getSelectedItem())){
            case "Azul":
                drawPanel.changePencilColor(new Color(135, 199, 255));
                break;
            case "Rojo":
                drawPanel.changePencilColor(new Color(237, 57, 57));
                break;
            case "Verde":
               drawPanel.changePencilColor(new Color(106,222,116));
               break;
            case "Amarillo":
               drawPanel.changePencilColor(new Color(248, 252, 131));
               break;
            case "Negro":
               drawPanel.changePencilColor(Color.BLACK);
               break;
        }
    }//GEN-LAST:event_pencilComboBoxActionPerformed

    private void drawPanelMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_drawPanelMouseMoved
       drawPanel.paint(evt.getX(), evt.getY());
       drawPanel.repaint();
    }//GEN-LAST:event_drawPanelMouseMoved


    /**
     * @param args the command line arguments
     * @throws java.lang.ClassNotFoundException
     * @throws java.lang.InstantiationException
     * @throws java.lang.IllegalAccessException
     * @throws javax.swing.UnsupportedLookAndFeelException
     */
    public static void main(String args[]) throws ClassNotFoundException, InstantiationException, IllegalAccessException, UnsupportedLookAndFeelException {
        
       UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new drawUI().setVisible(true);
       });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel authorsLabel;
    private javax.swing.JComboBox<String> backgroundComboBox;
    private javax.swing.JLabel backgroundLabel;
    private practica3.DrawablePanel drawPanel;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel optionPanel;
    private javax.swing.JComboBox<String> pencilComboBox;
    private javax.swing.JLabel pencilLabel;
    // End of variables declaration//GEN-END:variables
}
